# Generated by Django 2.2.14 on 2020-08-10 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interestArea', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_eula',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_eula_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_eula_version',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_general',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Intro Biography'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio_research_interest',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Outline of your Interests'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='connections',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Describe the connections and/or collaboration you are seeking.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='orcid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ORCID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
