# Generated by Django 2.2.16 on 2020-09-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200928_1133'),
        ('blog', '0002_auto_20200813_0950'),
    ]

    operations = [
    ]
