# Generated by Django 2.2.12 on 2020-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200512_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(default='title', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_sv',
            field=models.CharField(default='title', max_length=100, null=True),
        ),
    ]
