# Generated by Django 2.2.14 on 2020-08-13 09:50

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('name_en', models.SlugField(null=True)),
                ('name_sv', models.SlugField(null=True)),
                ('introduction', models.TextField()),
                ('introduction_en', models.TextField(null=True)),
                ('introduction_sv', models.TextField(null=True)),
                ('detailed_content', models.TextField()),
                ('detailed_content_en', models.TextField(null=True)),
                ('detailed_content_sv', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Work package',
                'verbose_name_plural': 'Work packages',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField()),
                ('title_en', models.SlugField(null=True)),
                ('title_sv', models.SlugField(null=True)),
                ('body', models.TextField()),
                ('body_en', models.TextField(null=True)),
                ('body_sv', models.TextField(null=True)),
                ('related_papers_tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('wp_parent', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='workpackages.WorkPackage', verbose_name='Work Package')),
            ],
            options={
                'verbose_name': 'Theme',
                'verbose_name_plural': 'Themes',
            },
        ),
    ]
