# Generated by Django 2.2.12 on 2020-05-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workpackages', '0002_auto_20200518_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='body_sv',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='title_sv',
            field=models.TextField(null=True),
        ),
    ]
