# Generated by Django 2.2.12 on 2020-05-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workpackages', '0003_auto_20200518_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='title',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title_en',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='title_sv',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='name',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='name_en',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='name_sv',
            field=models.SlugField(null=True),
        ),
    ]
