# Generated by Django 2.2.16 on 2020-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.BooleanField()),
                ('slug', models.SlugField()),
                ('category', models.SlugField(default='citizen-science')),
                ('title', models.CharField(default='title', max_length=100)),
                ('title_en', models.CharField(default='title', max_length=100, null=True)),
                ('title_sv', models.CharField(default='title', max_length=100, null=True)),
                ('published', models.DateField()),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_sv', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='PressPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('press_title', models.CharField(default='title', max_length=100)),
                ('press_title_en', models.CharField(default='title', max_length=100, null=True)),
                ('press_title_sv', models.CharField(default='title', max_length=100, null=True)),
                ('contact_Email', models.EmailField(max_length=254)),
                ('pressPublishedDate', models.DateField(db_index=True)),
                ('press_body', models.TextField()),
                ('press_body_en', models.TextField(null=True)),
                ('press_body_sv', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_title', models.CharField(default='title', max_length=100)),
                ('terms_title_en', models.CharField(default='title', max_length=100, null=True)),
                ('terms_title_sv', models.CharField(default='title', max_length=100, null=True)),
                ('version_number', models.CharField(default='v01', max_length=100)),
                ('terms_content', models.TextField()),
                ('terms_content_en', models.TextField(null=True)),
                ('terms_content_sv', models.TextField(null=True)),
            ],
        ),
    ]
