# Generated by Django 2.2.12 on 2020-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.SlugField(default='uncategorized'),
        ),
    ]
