# Generated by Django 2.2.16 on 2020-12-15 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Funding Body',
                'verbose_name_plural': 'Funding Bodies',
            },
        ),
        migrations.CreateModel(
            name='KeywordEng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_en', models.CharField(blank=True, max_length=20000, null=True)),
                ('summary_sv', models.CharField(blank=True, max_length=20000, null=True)),
                ('wikidataQ', models.IntegerField(blank=True, null=True)),
                ('keyword', models.TextField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ('keyword',),
            },
        ),
        migrations.CreateModel(
            name='KeywordLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordSwe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(db_index=True, unique=True)),
            ],
            options={
                'verbose_name': 'Keyword_sv',
                'verbose_name_plural': 'Keywords_sv',
                'ordering': ('keyword',),
            },
        ),
        migrations.CreateModel(
            name='OriginDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originDatabase', models.TextField()),
            ],
            options={
                'verbose_name': 'Origin Database',
                'verbose_name_plural': 'Origin Databases',
            },
        ),
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='The date the Project created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last date the Project was updated')),
                ('name', models.CharField(db_index=True, help_text='Common name for the project.', max_length=200)),
                ('aim', models.CharField(db_index=True, default='', help_text='Primary focus of the project.', max_length=600)),
                ('description', models.CharField(default='', max_length=50000)),
                ('status', models.CharField(choices=[('0', 'Not Selected'), ('1', 'Not yet started'), ('2', 'Active'), ('3', 'Periodically active'), ('4', 'On hold'), ('5', 'Completed'), ('6', 'Abandonded')], db_index=True, default='0', max_length=30)),
                ('start_date', models.DateTimeField(db_index=True, help_text='Date the project started.', null=True)),
                ('end_date', models.DateTimeField(db_index=True, help_text='Date the project ended.', null=True)),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Project url')),
                ('responsible_party_name', models.CharField(blank=True, max_length=50)),
                ('responsible_party_email', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, default='Not Provided', help_text='Name of the person maintaining this entry.', max_length=200)),
                ('contact_role', models.CharField(blank=True, default='Not Provided', help_text='Maintainer’s role or position with this project.', max_length=200)),
                ('contact_email', models.CharField(default='', max_length=200)),
                ('contact_phone', models.CharField(default='', max_length=200)),
                ('target_audience', models.CharField(db_index=True, default='', help_text='Project primary audience.', max_length=5000)),
                ('image_dir', models.CharField(default='', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exchanged', models.CharField(choices=[('DISABLED', 'Not Shared'), ('EXCHANGE', 'Sharing')], default='0', max_length=30)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('name_card', models.CharField(blank=True, db_index=True, help_text='Common name for the project.', max_length=30, verbose_name='Short Name (30 chars)')),
                ('aim_card', models.CharField(db_index=True, default='', help_text='Primary focus of the project.', max_length=100, verbose_name='Short aim (100 chars)')),
                ('description_card', models.CharField(default='', max_length=100, verbose_name='short description (100 chars)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('keywords', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Project Entry',
                'verbose_name_plural': 'Project Entries',
            },
        ),
        migrations.CreateModel(
            name='ProjectExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='The date the Project created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last date the Project was updated')),
                ('name', models.CharField(db_index=True, help_text='Common name for the project.', max_length=200)),
                ('aim', models.CharField(db_index=True, default='', help_text='Primary focus of the project.', max_length=600)),
                ('description', models.CharField(default='', max_length=50000)),
                ('status', models.CharField(choices=[('0', 'Not Selected'), ('1', 'Not yet started'), ('2', 'Active'), ('3', 'Periodically active'), ('4', 'On hold'), ('5', 'Completed'), ('6', 'Abandonded')], db_index=True, default='0', max_length=30)),
                ('start_date', models.DateTimeField(db_index=True, help_text='Date the project started.', null=True)),
                ('end_date', models.DateTimeField(db_index=True, help_text='Date the project ended.', null=True)),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Project url')),
                ('responsible_party_name', models.CharField(blank=True, max_length=50)),
                ('responsible_party_email', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, default='Not Provided', help_text='Name of the person maintaining this entry.', max_length=200)),
                ('contact_role', models.CharField(blank=True, default='Not Provided', help_text='Maintainer’s role or position with this project.', max_length=200)),
                ('contact_email', models.CharField(default='', max_length=200)),
                ('contact_phone', models.CharField(default='', max_length=200)),
                ('target_audience', models.CharField(db_index=True, default='', help_text='Project primary audience.', max_length=5000)),
                ('image_dir', models.CharField(default='', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exchanged', models.CharField(choices=[('DISABLED', 'Not Shared'), ('EXCHANGE', 'Sharing')], default='0', max_length=30)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('name_card', models.CharField(blank=True, db_index=True, help_text='Common name for the project.', max_length=30, verbose_name='Short Name (30 chars)')),
                ('aim_card', models.CharField(db_index=True, default='', help_text='Primary focus of the project.', max_length=100, verbose_name='Short aim (100 chars)')),
                ('description_card', models.CharField(default='', max_length=100, verbose_name='short description (100 chars)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
            ],
            options={
                'verbose_name': 'Project External',
                'verbose_name_plural': 'Project External',
            },
        ),
        migrations.CreateModel(
            name='ScienceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScienceType', models.TextField()),
            ],
            options={
                'verbose_name': 'Science Type',
                'verbose_name_plural': 'Science Types',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='The date the Project created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last date the Project was updated')),
                ('name', models.CharField(db_index=True, help_text='Common name for the project.', max_length=200)),
                ('aim', models.CharField(db_index=True, default='', help_text='Primary focus of the project.', max_length=600)),
                ('description', models.CharField(default='', max_length=50000)),
                ('status', models.CharField(choices=[('0', 'Not Selected'), ('1', 'Not yet started'), ('2', 'Active'), ('3', 'Periodically active'), ('4', 'On hold'), ('5', 'Completed'), ('6', 'Abandonded')], db_index=True, default='0', max_length=30)),
                ('start_date', models.DateTimeField(db_index=True, help_text='Date the project started.', null=True)),
                ('end_date', models.DateTimeField(db_index=True, help_text='Date the project ended.', null=True)),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='Project url')),
                ('responsible_party_name', models.CharField(blank=True, max_length=50)),
                ('responsible_party_email', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, default='Not Provided', help_text='Name of the person maintaining this entry.', max_length=200)),
                ('contact_role', models.CharField(blank=True, default='Not Provided', help_text='Maintainer’s role or position with this project.', max_length=200)),
                ('contact_email', models.CharField(default='', max_length=200)),
                ('contact_phone', models.CharField(default='', max_length=200)),
                ('target_audience', models.CharField(db_index=True, default='', help_text='Project primary audience.', max_length=5000)),
                ('image_dir', models.CharField(default='', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('exchanged', models.CharField(choices=[('DISABLED', 'Not Shared'), ('EXCHANGE', 'Sharing')], default='0', max_length=30)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('name_card', models.CharField(blank=True, db_index=True, help_text='Common name for the project.', max_length=30, verbose_name='Short Name (30 chars)')),
                ('aim_card', models.CharField(db_index=True, default='', help_text='Primary focus of the project.', max_length=100, verbose_name='Short aim (100 chars)')),
                ('description_card', models.CharField(default='', max_length=100, verbose_name='short description (100 chars)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images')),
                ('keywords_sv', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords_en', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Organization')),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
            },
        ),
    ]
