# Generated by Django 2.2.14 on 2020-08-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'Funding Body',
                'verbose_name_plural': 'Funding Bodies',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='OriginDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originDatabase', models.TextField()),
            ],
            options={
                'verbose_name': 'Origin Database',
                'verbose_name_plural': 'Origin Databases',
            },
        ),
        migrations.CreateModel(
            name='ScienceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScienceType', models.TextField()),
            ],
            options={
                'verbose_name': 'Science Type',
                'verbose_name_plural': 'Science Types',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='The date the Project created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last date the Project was updated')),
                ('name', models.CharField(db_index=True, help_text='Common name for the project.', max_length=200)),
                ('aim', models.CharField(db_index=True, default='', help_text='Primary focus of the project.', max_length=200)),
                ('description', models.CharField(default='', max_length=5000)),
                ('status', models.CharField(choices=[('0', 'Not Selected'), ('1', 'Not yet started'), ('2', 'Active'), ('3', 'Periodically active'), ('4', 'On hold'), ('5', 'Abandonded')], db_index=True, default='0', max_length=30)),
                ('start_date', models.DateTimeField(db_index=True, help_text='Date the project started.', null=True)),
                ('end_date', models.DateTimeField(db_index=True, help_text='Date the project ended.', null=True)),
                ('url', models.URLField(max_length=500)),
                ('responsible_party_name', models.CharField(blank=True, max_length=50)),
                ('responsible_party_email', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, default='Not Provided', help_text='Name of the person maintaining this entry.', max_length=200)),
                ('contact_role', models.CharField(blank=True, default='Not Provided', help_text='Maintainer’s role or position with this project.', max_length=200)),
                ('contact_affiliation', models.CharField(default='', help_text='Maintainer’s institutional affiliation.', max_length=200)),
                ('contact_email', models.CharField(default='', max_length=200)),
                ('contact_phone', models.CharField(default='', max_length=200)),
                ('target_audience', models.CharField(db_index=True, default='', help_text='Project primary audience.', max_length=5000)),
                ('image_dir', models.CharField(default='', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('exchanged', models.CharField(choices=[('DISABLED', 'Not Shared'), ('EXCHANGE', 'Sharing')], default='0', max_length=30)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(to='projects.Keyword')),
                ('science_type', models.ManyToManyField(to='projects.ScienceType')),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
            },
        ),
        migrations.CreateModel(
            name='ProjectExternal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='The date the Project created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last date the Project was updated')),
                ('name', models.CharField(db_index=True, help_text='Common name for the project.', max_length=200)),
                ('aim', models.CharField(db_index=True, default='', help_text='Primary focus of the project.', max_length=200)),
                ('description', models.CharField(default='', max_length=5000)),
                ('status', models.CharField(choices=[('0', 'Not Selected'), ('1', 'Not yet started'), ('2', 'Active'), ('3', 'Periodically active'), ('4', 'On hold'), ('5', 'Abandonded')], db_index=True, default='0', max_length=30)),
                ('start_date', models.DateTimeField(db_index=True, help_text='Date the project started.', null=True)),
                ('end_date', models.DateTimeField(db_index=True, help_text='Date the project ended.', null=True)),
                ('url', models.URLField(max_length=500)),
                ('responsible_party_name', models.CharField(blank=True, max_length=50)),
                ('responsible_party_email', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, default='Not Provided', help_text='Name of the person maintaining this entry.', max_length=200)),
                ('contact_role', models.CharField(blank=True, default='Not Provided', help_text='Maintainer’s role or position with this project.', max_length=200)),
                ('contact_affiliation', models.CharField(default='', help_text='Maintainer’s institutional affiliation.', max_length=200)),
                ('contact_email', models.CharField(default='', max_length=200)),
                ('contact_phone', models.CharField(default='', max_length=200)),
                ('target_audience', models.CharField(db_index=True, default='', help_text='Project primary audience.', max_length=5000)),
                ('image_dir', models.CharField(default='', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('exchanged', models.CharField(choices=[('DISABLED', 'Not Shared'), ('EXCHANGE', 'Sharing')], default='0', max_length=30)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(to='projects.Keyword')),
                ('science_type', models.ManyToManyField(to='projects.ScienceType')),
            ],
            options={
                'verbose_name': 'Project External',
                'verbose_name_plural': 'Project External',
            },
        ),
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='The date the Project created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Last date the Project was updated')),
                ('name', models.CharField(db_index=True, help_text='Common name for the project.', max_length=200)),
                ('aim', models.CharField(db_index=True, default='', help_text='Primary focus of the project.', max_length=200)),
                ('description', models.CharField(default='', max_length=5000)),
                ('status', models.CharField(choices=[('0', 'Not Selected'), ('1', 'Not yet started'), ('2', 'Active'), ('3', 'Periodically active'), ('4', 'On hold'), ('5', 'Abandonded')], db_index=True, default='0', max_length=30)),
                ('start_date', models.DateTimeField(db_index=True, help_text='Date the project started.', null=True)),
                ('end_date', models.DateTimeField(db_index=True, help_text='Date the project ended.', null=True)),
                ('url', models.URLField(max_length=500)),
                ('responsible_party_name', models.CharField(blank=True, max_length=50)),
                ('responsible_party_email', models.CharField(blank=True, max_length=50)),
                ('contact_name', models.CharField(blank=True, default='Not Provided', help_text='Name of the person maintaining this entry.', max_length=200)),
                ('contact_role', models.CharField(blank=True, default='Not Provided', help_text='Maintainer’s role or position with this project.', max_length=200)),
                ('contact_affiliation', models.CharField(default='', help_text='Maintainer’s institutional affiliation.', max_length=200)),
                ('contact_email', models.CharField(default='', max_length=200)),
                ('contact_phone', models.CharField(default='', max_length=200)),
                ('target_audience', models.CharField(db_index=True, default='', help_text='Project primary audience.', max_length=5000)),
                ('image_dir', models.CharField(default='', max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('exchanged', models.CharField(choices=[('DISABLED', 'Not Shared'), ('EXCHANGE', 'Sharing')], default='0', max_length=30)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(to='projects.Keyword')),
                ('science_type', models.ManyToManyField(to='projects.ScienceType')),
            ],
            options={
                'verbose_name': 'Project Entry',
                'verbose_name_plural': 'Project Entries',
            },
        ),
    ]
