# Generated by Django 2.2.12 on 2020-05-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aim', models.CharField(default='', help_text='Primary focus of the project.', max_length=200)),
                ('description', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', help_text='Common name for the project.', max_length=200)),
                ('start_date', models.DateTimeField(help_text='Date the project started.', null=True)),
                ('end_date', models.DateTimeField(help_text='Date the project concluded.', null=True)),
                ('status', models.CharField(choices=[('0', 'Not Selected'), ('1', 'Not yet started'), ('2', 'Active'), ('3', 'Periodically active'), ('4', 'On hold'), ('5', 'Abandonded')], default='0', max_length=30)),
                ('target_audience', models.CharField(default='', help_text='Project primary audience.', max_length=5000)),
                ('contact_name', models.CharField(default='', help_text='Name of the person maintaining this entry. Default is your account.', max_length=200)),
                ('contact_role', models.CharField(default='', help_text='Maintainer’s role or position with this project.', max_length=200)),
                ('contact_affiliation', models.CharField(default='', help_text='Maintainer’s institutional affiliation.', max_length=200)),
                ('contact_email', models.CharField(default='', max_length=200)),
                ('contact_phone', models.CharField(default='', max_length=200)),
                ('keywords', models.ManyToManyField(to='projects.Keyword')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
