# Generated by Django 3.0.3 on 2020-02-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='aim',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Empty', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Empty', max_length=200),
        ),
    ]
