# Generated by Django 2.2.14 on 2020-07-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_dir',
            field=models.CharField(default='', max_length=200),
        ),
    ]
