# Generated by Django 2.2.16 on 2021-02-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201215_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectentry',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectentry',
            name='originDatabase',
            field=models.CharField(choices=[('0', 'ARCS'), ('1', 'EUCitizenScience')], db_index=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='projectexternal',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectexternal',
            name='originDatabase',
            field=models.CharField(choices=[('0', 'ARCS'), ('1', 'EUCitizenScience')], db_index=True, default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='originDatabase',
            field=models.CharField(choices=[('0', 'ARCS'), ('1', 'EUCitizenScience')], db_index=True, default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='The date the Project created'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last date the Project was updated'),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='url',
            field=models.FileField(blank=True, max_length=500, upload_to='', verbose_name='Project url'),
        ),
        migrations.AlterField(
            model_name='projectexternal',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='The date the Project created'),
        ),
        migrations.AlterField(
            model_name='projectexternal',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last date the Project was updated'),
        ),
        migrations.AlterField(
            model_name='projectexternal',
            name='url',
            field=models.FileField(blank=True, max_length=500, upload_to='', verbose_name='Project url'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='The date the Project created'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last date the Project was updated'),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='url',
            field=models.FileField(blank=True, max_length=500, upload_to='', verbose_name='Project url'),
        ),
    ]
