# Generated by Django 3.0.3 on 2020-02-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_affiliation',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_email',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_name',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(default='Empty', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='contact_role',
            field=models.CharField(default='Empty', max_length=200),
        ),
    ]
