# Generated by Django 2.2.12 on 2020-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20200429_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterField(
            model_name='project',
            name='aim',
            field=models.CharField(default='', help_text='Primary focus of the project.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_affiliation',
            field=models.CharField(default='', help_text='Maintainer’s institutional affiliation.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_name',
            field=models.CharField(default='', help_text='Name of the person maintaining this entry. Default is your account.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='contact_role',
            field=models.CharField(default='', help_text='Maintainer’s role or position with this project.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Date the project concluded.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', help_text='Common name for the project.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date the project started.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('0', 'Not yet started'), ('1', 'Active'), ('2', 'Periodically active'), ('3', 'On hold'), ('4', 'Abandonded')], default='Empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_audience',
            field=models.CharField(default='', help_text='Project primary audience.', max_length=5000),
        ),
    ]
