# Generated by Django 2.2.12 on 2020-05-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20200506_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(help_text='Date the project concluded.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(help_text='Date the project started.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('0', 'Not Selected'), ('1', 'Not yet started'), ('2', 'Active'), ('3', 'Periodically active'), ('4', 'On hold'), ('5', 'Abandonded')], default='0', max_length=30),
        ),
    ]
