# Generated by Django 2.2.12 on 2020-05-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20200506_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
    ]
