# Generated by Django 2.2.16 on 2020-12-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField()),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=20000)),
                ('title_en', models.CharField(default='title', max_length=20000, null=True)),
                ('title_sv', models.CharField(default='title', max_length=20000, null=True)),
                ('abstract', models.CharField(default='Empty', max_length=50000)),
                ('abstract_en', models.CharField(default='Empty', max_length=50000, null=True)),
                ('abstract_sv', models.CharField(default='Empty', max_length=50000, null=True)),
                ('doi', models.CharField(blank=True, help_text='DOI without http', max_length=20000)),
                ('py', models.IntegerField(default='0000', help_text='Publication Year - YYYY')),
                ('authors', models.CharField(default='Author', help_text='Author String', max_length=50000)),
                ('source', models.CharField(blank=True, help_text='Source Name', max_length=20000)),
                ('volume', models.CharField(blank=True, help_text='Volume', max_length=20000)),
                ('issue', models.CharField(blank=True, help_text='Issue Number', max_length=20000)),
                ('keywords', models.ManyToManyField(related_name='Article', to='projects.KeywordEng')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
