# Generated by Django 2.2.12 on 2020-05-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.TextField(default='keyword')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=200)),
                ('title_en', models.CharField(default='title', max_length=200, null=True)),
                ('title_sv', models.CharField(default='title', max_length=200, null=True)),
                ('abstract', models.CharField(default='Empty', max_length=5000)),
                ('abstract_en', models.CharField(default='Empty', max_length=5000, null=True)),
                ('abstract_sv', models.CharField(default='Empty', max_length=5000, null=True)),
                ('doi', models.CharField(default='doi', max_length=200)),
                ('py', models.IntegerField(default='0')),
                ('authors', models.CharField(default='Author', max_length=500)),
                ('source', models.CharField(default='Journal Name', max_length=200)),
                ('volume', models.CharField(default='Volume', max_length=200)),
                ('issue', models.CharField(default='Issue', max_length=200)),
                ('keywords', models.ManyToManyField(to='publications.Keyword')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
