# Generated by Django 2.2.12 on 2020-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20200430_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.CharField(default='Issue', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.CharField(default='Journal Name', max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='volume',
            field=models.CharField(default='Volume', max_length=200),
        ),
    ]
