# Generated by Django 2.2.12 on 2020-05-12 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20200504_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arcsreport',
            options={'verbose_name': 'Arcs Report', 'verbose_name_plural': 'Arcs Reports'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Keyword', 'verbose_name_plural': 'Keywords'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publicaiton', 'verbose_name_plural': 'Publicaitons'},
        ),
    ]
