# Generated by Django 2.2.12 on 2020-05-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20200512_0921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
        migrations.AddField(
            model_name='article',
            name='abstract_en',
            field=models.CharField(default='Empty', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='abstract_sv',
            field=models.CharField(default='Empty', max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_sv',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
